### ISSUE TITLE
README mentions a .exe which is not in the repo

### ISSUE THREAD

**Issue by toto-jy** [sander/plak#2]
The README mentions to drag Plak.Windows.exe to the startup folder, but there is no such file in the repo when cloned. There is a bare folder called Plak.Windows, but this is not a .exe.

Is there a step missing that is required to build the .exe?

**Comment by sander** [comment]
Indeed that instruction step is still missing from the README. You need to open `plan.sln` with Visual Studio (Community edition will suffice) and build the project to get `Plak.Windows.exe`.

**Comment by sander** [comment]
Clarified in 274c005.
